version: "3"
services:
  oracle:
    image: gvenzl/oracle-free:latest
    platform: linux/amd64
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=pixelplay123
      - APP_USER=pixelplay
      - APP_USER_PASSWORD=pixelplay123
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  oracle-data:
