version: "3"

services:
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: pixelplay_oracle
    environment:
      - ORACLE_PASSWORD=pixelplay123
      - ORACLE_DATABASE=FREE
      - APP_USER=pixelplay
      - APP_USER_PASSWORD=pixelplay123
    ports:
      - "1521:1521"
    volumes:
      - ./oracle_data:/opt/oracle/oradata
      - ./estructura_pixelplay.sql:/container-entrypoint-initdb.d/01_estructura.sql
      - ./datos_pixelplay.sql:/container-entrypoint-initdb.d/02_datos.sql
    healthcheck:
      test:
        [
          "CMD",
          "sqlplus",
          "-L",
          "system/pixelplay123@//localhost:1521/FREE",
          "@healthcheck.sql",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
